
/**
 * QPXExpressAPILib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 02/24/2016
 */
var BaseModel = require("./BaseModel");
/**
 * Creates a instance of TripsSearchRequest
 *
 * @constructor
 */
function TripsSearchRequest() {
    this.request = null;     
}

TripsSearchRequest.prototype = new BaseModel();
TripsSearchRequest.prototype.constructor = BaseModel;

/**
 * A QPX Express search request. Required values are at least one adult or senior passenger, an origin, a destination, and a date.
 *
 * @return {TripOptionsRequest|null}
 */
TripsSearchRequest.prototype.getRequest = function() {
    return this.request;
};

/**
 * Setter for Request
 * 
 * @param {TripOptionsRequest|null} value 
 */
TripsSearchRequest.prototype.setRequest = function(value) {
    this.request = value;
};

module.exports = TripsSearchRequest;