/**
 * QPXExpressAPILib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 02/24/2016
 */

var configuration = {
    //The base Uri for API calls
    BASEURI : "https://www.googleapis.com/qpxExpress/v1/trips"

};

module.exports = configuration;

